### PR TITLE
Added CSS font-family override !important note to manual.txt

### PR DESCRIPTION
**Pull request by evandrocoan**
Add a note for: https://anki.tenderapp.com/discussions/beta-testing/1832-the-id-selector-typeans-font-size-50px-is-not-working

### CODE REVIEW

**Comment by dae** [comment]
The 'checking your answer' section describes that you can change the font size by adjusting it in the Fields dialog already. And a little above the text you entered, is a note specifically saying that section does not cover typing in the answer :-)

**Comment by evandrocoan** [comment]
It says it does not cover "change the font for type answer and etc" but does not specify it does not cover the font size. Although, using `!important` you can also change the font type.

I would prefer to use CSS with `!important` because it does not affects all card types for the specified field and give the user full control of the styling by using CSS without depending on Anki UI options for font-size/type.

In my opinion, add the existence of the `!important` tag would be a great addition for the Anki Docs. Until now, I did not know about the existence of the `!important` keyword. I only found out about it, when I figured out the font size was not being applied due the usage of the inline styling.

But not having this on the docs would either not stop other users from finding this out by themselves like I did. However, it could be more difficult if they do not look inside the Anki code base or knew before-hand about the existence of the CSS `!important` keyword.

I changed a little the wording of the new note to see if you like how it is now. Do you have another suggestion of how I could introduce the `!important` keyword? If not, then you can either merge or close it the pull request.

**Comment by dae** [comment]
Anki generally tries not to use styling that would require !important to override. Can you think of any other examples except the typing box that requires it? If not, I think it's probably better mentioned in the typing section.

**Comment by evandrocoan** [comment]
I cannot think of other usages right now. Then, I moved it to the `typing section`.

**Comment by dae** [comment]
cheers

**Pull request merged**
